export const CREATE_LIST_ALLTIME = 'CREATE_LIST_ALLTIME';
export const CREATE_LIST_RECENT = 'CREATE_LIST_RECENT';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAILED = 'DATA_FAILED';
export const ORDER_ALLTIME = 'ORDER_ALLTIME';
export const ORDER_RECENT = 'ORDER_RECENT';
